/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RegistroUsuario;

/**
 *
 * @author Sebas
 */
public class UsuarioNuevo extends javax.swing.JFrame {
    private static UsuarioNuevo agregarUsuario;

    private UsuarioNuevo(){
        initComponents();
    }
    public static UsuarioNuevo getInstance() {
        if (agregarUsuario== null) {
          agregarUsuario = new UsuarioNuevo();
        }
        return agregarUsuario;
    }

    /**
     * Creates new form UsuarioNuevo
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TxtNombreUs = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("GAMERIA", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 235, 173));
        jLabel1.setText("REGISTRO USUARIO");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre Usuario"));
        jPanel2.setLayout(new java.awt.GridLayout());

        TxtNombreUs.setText("jTextField1");
        TxtNombreUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreUsActionPerformed(evt);
            }
        });
        jPanel2.add(TxtNombreUs);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout());

        jTextField1.setText("jTextField1");
        jPanel3.add(jTextField1);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout());

        jTextField2.setText("jTextField2");
        jPanel4.add(jTextField2);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreUsActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtNombreUs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
