/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Juegos;

import javax.swing.JOptionPane;
import MenuPrincipal.Menu;
/**
 *
 * @author Sebas
 */
public class CompraJuegos extends javax.swing.JFrame {

    /**
     * Creates new form JuegosPc
     */
    public CompraJuegos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblDiablo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ChbDiablo = new javax.swing.JCheckBox();
        ChbGta = new javax.swing.JCheckBox();
        ChbDestiny = new javax.swing.JCheckBox();
        ChbGoW = new javax.swing.JCheckBox();
        ChbBattle = new javax.swing.JCheckBox();
        ChbHalo = new javax.swing.JCheckBox();
        BtnAñadir = new javax.swing.JButton();
        BtnMostrar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("GAMERIA", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("PC");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel12.setText("Play Station");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel13.setText("X Box");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        lblDiablo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sebas\\Desktop\\APO3\\IMAGENES\\DIABLO.png")); // NOI18N
        lblDiablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDiabloMouseClicked(evt);
            }
        });
        jPanel2.add(lblDiablo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sebas\\Desktop\\APO3\\IMAGENES\\gta.jpeg")); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 130, 120));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sebas\\Desktop\\APO3\\IMAGENES\\dest.jpg")); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 130, 120));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sebas\\Desktop\\APO3\\IMAGENES\\good.jpg")); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 140));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sebas\\Desktop\\APO3\\IMAGENES\\btf.jpg")); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 120, 140));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sebas\\Desktop\\APO3\\IMAGENES\\halo.png")); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, 140));

        ChbDiablo.setText("Diablo");
        ChbDiablo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChbDiabloActionPerformed(evt);
            }
        });
        jPanel2.add(ChbDiablo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        ChbGta.setText("GTA V");
        ChbGta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChbGtaActionPerformed(evt);
            }
        });
        jPanel2.add(ChbGta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        ChbDestiny.setText("Destiny");
        jPanel2.add(ChbDestiny, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        ChbGoW.setText("Good Of War");
        jPanel2.add(ChbGoW, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        ChbBattle.setText("Battle Field");
        jPanel2.add(ChbBattle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        ChbHalo.setText("Halo Reach");
        jPanel2.add(ChbHalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        BtnAñadir.setText("Añadir");
        BtnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñadirActionPerformed(evt);
            }
        });
        jPanel2.add(BtnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        BtnMostrar.setText("Mostrar");
        BtnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDiabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDiabloMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_lblDiabloMouseClicked

    private void ChbDiabloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChbDiabloActionPerformed
        // TODO add your handling code here:
         
        
        
    }//GEN-LAST:event_ChbDiabloActionPerformed

    private void BtnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñadirActionPerformed
        // TODO add your handling code here:
        String juegos="";
        if(ChbDiablo.isSelected()){
            juegos=ChbDiablo.getText()+"Diablo, ";
        }
        if(ChbBattle.isSelected()){
            juegos=ChbBattle.getText()+"Battle Field, ";
        }
        if(ChbDestiny.isSelected()){
            juegos=ChbDestiny.getText()+"Destiny, ";
        }
        if(ChbGoW.isSelected()){
            juegos=ChbGoW.getText()+"God of War, ";
        }
        if(ChbGta.isSelected()){
            juegos=ChbGta.getText()+"GTA V, ";
        }
        if(ChbHalo.isSelected()){
            juegos=ChbHalo.getText()+"Halo, ";
        }
        
        
    }//GEN-LAST:event_BtnAñadirActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
        Menu menuprincipal = Menu.getInstance();
        menuprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void ChbGtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChbGtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChbGtaActionPerformed

    private void BtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_BtnMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAñadir;
    private javax.swing.JButton BtnMostrar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JCheckBox ChbBattle;
    private javax.swing.JCheckBox ChbDestiny;
    private javax.swing.JCheckBox ChbDiablo;
    private javax.swing.JCheckBox ChbGoW;
    private javax.swing.JCheckBox ChbGta;
    private javax.swing.JCheckBox ChbHalo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDiablo;
    // End of variables declaration//GEN-END:variables
}
